#ifndef PALETTE_H_INCLUDED
#define PALETTE_H_INCLUDED

#include<allegro5/allegro.h>
#include<stdint.h>

#define PAL_LEN			56
#define GRAYSCALE_LEN	8
#define RGBA_LEN		4
// for access to color array
#define RGBA_RED		0
#define RGBA_GREEN		1
#define RGBA_BLUE		2
#define RGBA_ALPHA		3

// NES color palette

enum PAL_COLOR_ID {
	BLACK = 0x00,
	WHITE = 0x01,
	WHITE_GRAY = 0x02,
	LIGHT_GRAY = 0x03,
	GRAY = 0X04,
	SKY_WHITE_LIGHT_BLUE = 0X05,
	SKY_LIGHT_BLUE = 0X06,
	SKY_BLUE = 0X07,
	SKY_DARK_BLUE = 0X08,
	WHITE_LIGHT_MARINE_BLUE = 0X09,
	LIGHT_MARINE_BLUE = 0X0A,
	MEDIUM_MARINE_BLUE = 0X0B,
	MARINE_BLUE = 0X0C,
	WHITE_LIGHT_LAVANDA = 0X0D,
	LIGHT_LAVANDA = 0X0E,
	LAVANDA = 0X0F,
	DARK_LAVANDA = 0X10,
	WHITE_LIGHT_PINK_1 = 0X11,
	LIGHT_PINK_1 = 0X12,
	MAGENTA = 0X13,
	DARK_MAGENTA = 0X14,
	WHITE_LIGHT_PINK_2 = 0X15,
	PINK = 0X16,
	DARK_PINK = 0X17,
	RED = 0X18,
	WHITE_LIGHT_ORANGE = 0X19,
	LIGHT_ORANGE = 0X1A,
	ORANGE = 0X1B,
	DARK_RED = 0X1C,
	WHITE_LIGHT_GOLDEN = 0X1D,
	LIGHT_AMBAR = 0X1E,
	AMBAR = 0X1F,
	BROWN_RED = 0X20,
	LIGHT_GOLDEN = 0X21,
	YELLOW = 0X22,
	DARK_YELLOW = 0X23,
	BROWN = 0X24,
	WHITE_LIGHT_LIME_GREEN = 0X25,
	LIGHT_LIME_GREEN = 0X26,
	LIME_GREEN = 0X27,
	DARK_LIME_GREEN = 0X28,
	LIGHT_SPRINGGREEN = 0X29,
	SPRINGGREEN = 0X2A,
	GREEN = 0X2B,
	DARK_GREEN = 0X2C,
	MINT_GREEN = 0X2D,
	FOAM_GREEN = 0X2E,
	JADE_GREEN = 0X2F,
	FOREST_GREEN = 0X30,
	LIGHT_CYAN = 0X31,
	CYAN = 0X32,
	DARK_CYAN = 0X33,
	OCEAN = 0X34,
	LAVENDER_BUSH = 0X35,
	GRAY_2 = 0x36	
};


uint8_t GRAYSCALE[GRAYSCALE_LEN][RGBA_LEN];
uint8_t PALETTE[PAL_LEN][RGBA_LEN];

#endif
